### ISSUE TITLE
Question regarding copyrights

### ISSUE THREAD

**Issue by CaitlinKIN** [darsain/fpsmeter#10]
Hello. I work at a company that is making a software manual for a client. The manual will be made in Japanese then translated into English. Within the manual, there is a brief mention of "FPSMeter". For this reason, we would like to know if you require us to include a copyright phrase in our manual for your product. If so, could you please tell us what copyright phrase to use? (English only is fine.) Also, if you require some trademark attribution phrase ("FPSMeter   is a trademark of..."), please let us know. If you need more specific details, please email me at beggs@kinsha.co.jp. Thank you for your time!

**Comment by darsain** [comment]
No attribution or trademarks or anything needed. FPSMeter license is MIT, which is currently mentioned only in package.json file on [line 21](https://github.com/darsain/fpsmeter/blob/e86d0303e424148c67afd9ce082caf9aac711bd0/package.json#L21) because I'm lazy to setup and maintain any LICENSE.md files :)

**Comment by CaitlinKIN** [comment]
Thank you!
