### ISSUE TITLE
npm - Help browserify fans

### ISSUE THREAD

**Issue by alexanderGugel** [darsain/fpsmeter#5]
Great work!

Would you mind publishing this to the npm registry? I would love to use this with browserify. The package.json is already there, the only thing that's missing is referencing the main file in package.json and updating the version number.

https://www.npmjs.org/doc/cli/npm-publish.html

**Comment by darsain** [comment]
I'm planning to convert all of my older libs like this one into a component/duo components, which will make them impossible to consume by bower or browserify, unless I keep having the `dist` folder with built standalone version in the repository, which I despise with every cell of my body. I've already removed bower integration from all of my projects.

I'll definitely be publishing the standalone build to some CDNs though. It's useful when isolating issues on jsfiddle, but poor souls not using component/duo can use it too. They'll get a file full of inlined dependencies and redundant UMD, but what can I do... I want to have a comfortable and nice to work with development environment & ecosystem, and that is just not compatible with how bower & browserify work.

I was thinking about how to do something like:

``` js
{
  main: '//path.to/cdn.js'
}
```

But that 1.) doesn't work, and 2.) I'd advice against using this kind of packages, as they inline all the dependencies that than can't be reused, which result's into bloated build files.

So it'll be duo or a standalone file on CDN from now on. Everything else is unreasonable, requires compromises, and results into inefficient builds in different ecosystems. And I don't want to encourage that.

Sorry about that :(

**Comment by alexanderGugel** [comment]
I understand your motivation, but I think that this is an issue that can be easily resolved. Even if you don't like having a `dist` folder (nobody does), browserify can still be used. Instead of `require('fpsmeter')`, you would write `require('fpsmeter/src/whatever')`. This is ugly, but duo isn't widespread (yet). Therefore I think that it makes sense to make this repo compatible with bower and browserify. There are options how this can be done.

For instance, transforms can specified in your package.json:

``` json
  "dependencies": {
    "deamdify": "^0.1.1"
  },
  "browserify": {
    "transform": "deamdify"
  }
```

(stolen from [Famo.us](https://github.com/Famous/famous/blob/master/package.json) - I know you're not using AMD, but I wanted to demonstrate that the JS consumed by browserify users can be modified beforehand)

Another option would be to specify a [postinstall](https://www.npmjs.org/doc/misc/npm-scripts.html) script, which would build everything and create the `dist` folder.

I really don't get the problem here. I know this is an ugly solution, but relying in duo alone is currently probably not such a good idea..

**Comment by alexanderGugel** [comment]
Sorry, I didn't address bower - anyways: Does this change anything or am I missing something? I think the way [Backbone](https://github.com/jashkenas/backbone) does this is quite elegant. I think there is a misconception that the file required by browserify needs to be minifed and built.

Cheers,
Alex

**Comment by darsain** [comment]
The issue is that creating a proper component/duo package means offloading everything not related to the package to dependencies, because having every other package inline its proprietary event binding, event emitter, object extend, and other implementations is just retarded.

The component/duo dependencies are namespaced pointers to github repos (one of the awesome features of the two):

``` js
"dependencies": {
  "darsain/event": "~0.1.0"
}
```

Some might have an npm alternative, some won't. And going through aliases, try/caching require calls, and overall publishing any frontend stuff to the horrible npm just makes me cry :(

I think I'll try making it browserify friendly, but even than... I'm planning to move templates to CSS, because it just makes sense. It didn't at the start because I wanted it to be easily consumable, just include one file and be done, but it does now because both component & duo have support for other assets like CSS & building CSS from required components. So in there it's just a seamless integration you don't even notice. In browserify you'd have to still copy & paste the CSS either from what npm downloads, or from the repository, basically defeating the purpose of having package manager.

I'm also really trying to not have to publish any frontend thing to npm :) Browserify is a hacky solution that inherits everything bad about npm.

If you could be satisfied by using npm's github support:

``` js
"dependencies" : {
  "fpsmeter": "darsain/fpsmeter#commit-ish", // not sure the #commit-ish is supported here
  // or
  "fpsmeter": "git://github.com/darsain/fpsmeter.git#commit-ish"
}
```

It'd be awesome. But you loose the ability to specify version ranges, or does npm finally support that? Last time I checked it didn't, and there is no mention of it in docs :/ Just a few opened requests on npm repo.

**Comment by darsain** [comment]
If you'd be satisfied with npm's github support, I think I'd even just merge your PR, and forget about this repo :)

Apart of the rewrite into a "proper package", there is not much more to be done here. It's basically finished. So I wouldn't mind not doing anything to it anymore, which would keep it (with your PR) browserify friendly :)

But I just really don't want to publish to npm :no_mouth:

**Comment by alexanderGugel** [comment]
Hey @darsain ,

ok, makes sense :) Thanks for clarifying your intentions etc. :)

Cheers,
Alex

**Comment by darsain** [comment]
Merged.

**Comment by darsain** [comment]
Just a reminder, please point to #comitish in your package.json. That way it won't break when master changes.
